dependencies:
  - python=3.8
  - numpy
  - matplotlib==3.2.1
  - numpy==1.21.0
  - scipy==1.4.1              # via seaborn
  - cxroots
  - sympy==1.7.1
  - ipywidgets==8.0.0
  - fpdf==1.7.2
  - pillow==8.3.0
